[custom.all.sop]
type = "local"
path = "."
ipkg = "sop.ipkg"

[custom.all.sop-docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:derive"
ipkg   = "elab-util.ipkg"
